networks:
  ddd-starter-pack-network:
    name: ddd-starter-pack-network
    driver: bridge

volumes:
  ddd-starter-pack-database-volume: {}

services:
  ddd-starter-pack-php:
    image: ddd-starter-pack-php
    build: php
    hostname: dddsp
    volumes:
      - ../:/var/www/app
      - ./data/shell_history:/home/utente/shell_history
    networks:
      - ddd-starter-pack-network
    environment:
      - HISTFILE=/home/utente/shell_history/.x_history

  ddd-starter-pack-db:
    image: mariadb:10.3.22
    volumes:
      - ddd-starter-pack-database-volume:/var/lib/mysql
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ddd_sp_test
    command: mysqld --sql_mode="" #Per mysql, non serve per mariadb
    networks:
      - ddd-starter-pack-network

  conventional-commit-nodejs:
    image: conventional-commit-nodejs
    build: nodejs
    working_dir: /var/www/app
    #command: "commitlint -e --from=HEAD"
    volumes:
      - ../:/var/www/app
    networks:
      - ddd-starter-pack-network
